-- Made by sheets.lua at mod init (sheets_create): the seals a sheet may carry, in tiers
SHEET_LIST = {
	{ key = "floatglow", name = "Floatglow Lamp", element = "light", tier = 1 },
	{ key = "floating_drops", name = "Floating Drops", element = "storm", tier = 1 },
	{ key = "flowers_of_light", name = "Flowers of Light", element = "light", tier = 1 },
	{ key = "flowers_of_sand", name = "Flowers of Sand", element = "sand", tier = 1 },
	{ key = "flying_watersculptures", name = "Flying Watersculptures", element = "water", tier = 1, book = "quire" },
	{ key = "forbidden_glow", name = "Forbidden Glow", element = "flicker", tier = 1 },
	{ key = "glowstone_path", name = "Glowstone Path", element = "light", tier = 1 },
	{ key = "light_beam", name = "Light Beam", element = "light", tier = 1, book = "quire" },
	{ key = "loop_chalice", name = "Loop Chalice", element = "light", tier = 1 },
	{ key = "phantasmal_fireball", name = "Phantasmal Fireball", element = "fire", tier = 1 },
	{ key = "playland_of_sand", name = "Playland of Sand", element = "sand", tier = 1 },
	{ key = "rainbringer", name = "Rainbringer", element = "water", tier = 1 },
	{ key = "rainflinger", name = "Rainflinger", element = "firestorm", tier = 1, book = "quire" },
	{ key = "sewer_grate", name = "Sewer Grate", element = "water", tier = 1, book = "quire" },
	{ key = "washbarrel", name = "Washbarrel", element = "light", tier = 1 },
	{ key = "water_rose", name = "Water Rose", element = "water", tier = 1 },
	{ key = "watersculpture", name = "Watersculpture", element = "water", tier = 1, book = "quire" },
	{ key = "watershot", name = "Watershot", element = "water", tier = 1 },
	{ key = "billow_cluster", name = "Billow Cluster", element = "sand", tier = 2, book = "quire" },
	{ key = "bird_of_light", name = "Bird of Light Beacon", element = "light", tier = 2, book = "quire" },
	{ key = "boulder_stretch", name = "Boulder Stretch Rope", element = "earth", tier = 2 },
	{ key = "crystal_ribbon", name = "Crystal Ribbon", element = "crystal", tier = 2 },
	{ key = "everflow", name = "Everflow", element = "water", tier = 2, book = "quire" },
	{ key = "floatglow_anchored", name = "Wall-Anchored Floatglow Lamp", element = "beam", tier = 2 },
	{ key = "glowing_owlcat", name = "Glowing Owlcat", element = "light", tier = 2, book = "quire" },
	{ key = "grasping_wind", name = "Grasping Wind", element = "wind", tier = 2, book = "quire" },
	{ key = "integration", name = "Integration", element = "earth", tier = 2 },
	{ key = "leech_of_light", name = "Valance Leech of Light", element = "light", tier = 2 },
	{ key = "looking_glass", name = "Looking Glass", element = "light", tier = 2 },
	{ key = "makeover_mask", name = "Makeover Mask", element = "smoke", tier = 2, book = "quire" },
	{ key = "purify", name = "Purify", element = "water", tier = 2 },
	{ key = "pyreball", name = "Pyreball", element = "fire", tier = 2, book = "quire" },
	{ key = "ring_of_fire", name = "Ring of Fire", element = "fire", tier = 2, book = "quire" },
	{ key = "smokesculpture", name = "Smokesculpture", element = "smoke", tier = 2, book = "quire" },
	{ key = "snow_walking", name = "Snow-walking Spell", element = "wind", tier = 2 },
	{ key = "snowfending", name = "Snowfending", element = "firestorm", tier = 2 },
	{ key = "snugstone", name = "Snugstone", element = "fire", tier = 2 },
	{ key = "vapor_bubble", name = "Vapor Bubble", element = "storm", tier = 2 },
	{ key = "warmth_retention", name = "Warmth-Retention", element = "light", tier = 2 },
	{ key = "water_horse", name = "Water Horse", element = "water", tier = 2 },
	{ key = "bubble_carriage", name = "Bubble Carriage", element = "air", tier = 3 },
	{ key = "carousel", name = "Carousel of Lights", element = "light", tier = 3 },
	{ key = "earth_lift", name = "Earth Lift", element = "earth", tier = 3 },
	{ key = "flame_shot", name = "Flame Shot", element = "fire", tier = 3 },
	{ key = "flying_puppet", name = "Flying Puppet of Diversion", element = "wind", tier = 3 },
	{ key = "forbidden_flames", name = "Forbidden Flames", element = "light", tier = 3 },
	{ key = "giant_water_puppet", name = "Giant Water Puppet of Diversion", element = "water", tier = 3 },
	{ key = "icy_road", name = "Icy Road", element = "crystal", tier = 3 },
	{ key = "mist_basin", name = "Mist Basin", element = "storm", tier = 3, book = "quire" },
	{ key = "pouch_guidance", name = "Pouch Guidance", element = "wind", tier = 3 },
	{ key = "pouch_of_calling", name = "Pouch of Calling", element = "beam", tier = 3, book = "quire" },
	{ key = "replication", name = "Replication Magic", element = "earth", tier = 3 },
	{ key = "rising_platform", name = "Rising Platform of Water", element = "water", tier = 3 },
	{ key = "river_ferry", name = "River Ferry", element = "wind", tier = 3 },
	{ key = "sand_bridge", name = "Sand Bridge", element = "sand", tier = 3 },
	{ key = "smoke_cloud", name = "Smoke Cloud", element = "smoke", tier = 3 },
	{ key = "sourcewater", name = "Sourcewater Strike", element = "water", tier = 3 },
	{ key = "wall_bend", name = "Wall Bend", element = "earth", tier = 3 },
	{ key = "wand_of_water", name = "Wand of Water", element = "water", tier = 3 },
	{ key = "wash_spring", name = "Wash Spring", element = "light", tier = 3 },
	{ key = "water_bolt_27", name = "Great Water Bolt", element = "ice", tier = 3 },
	{ key = "water_orb", name = "Water Orb", element = "water", tier = 3 },
	{ key = "waterflinger", name = "Waterflinger", element = "steam", tier = 3, book = "quire" },
	{ key = "ancient_light_beacon", name = "Ancient Light Beacon", element = "light", tier = 4, book = "tome" },
	{ key = "beastwarding", name = "Beastwarding", element = "crystal", tier = 4 },
	{ key = "capture_pennant", name = "Capture Pennant", element = "light", tier = 4 },
	{ key = "fish_guidance", name = "Fish Guidance", element = "smoke", tier = 4 },
	{ key = "frozen_path", name = "Frozen Path", element = "ice", tier = 4 },
	{ key = "illusion_cloak", name = "Beldaruit's Illusion Cloak", element = "wind", tier = 4 },
	{ key = "light_reducing", name = "Light-Reducing Spell", element = "crystal", tier = 4, book = "tome" },
	{ key = "light_tracer", name = "Light Tracer", element = "light", tier = 4 },
	{ key = "lightning_spell", name = "Lightning Spell", element = "thunder", tier = 4, book = "quire" },
	{ key = "rainwarding", name = "Rainwarding", element = "light", tier = 4 },
	{ key = "rising_wave", name = "Rising Wave", element = "water", tier = 4 },
	{ key = "sand_cage", name = "Sand Cage", element = "light", tier = 4 },
	{ key = "serpents_bed", name = "Serpent's Bed of Sand", element = "light", tier = 4, book = "tome" },
	{ key = "spike", name = "Spike", element = "earth", tier = 4 },
	{ key = "spiraling_flame", name = "Spiraling Flame", element = "fire", tier = 4, book = "quire" },
	{ key = "sprite_winged", name = "Sprite-Winged Smokesculpture", element = "smoke", tier = 4 },
	{ key = "torchstag", name = "Torchstag", element = "fire", tier = 4, book = "quire" },
	{ key = "tracking", name = "Tracking Spell", element = "light", tier = 4 },
	{ key = "wall_breaker", name = "Wall Breaker", element = "earth", tier = 4, book = "quire" },
	{ key = "wallwarding", name = "Wallwarding", element = "earth", tier = 4 },
	{ key = "water_bolt_archives", name = "Threefold Water Bolt", element = "ice", tier = 4 },
	{ key = "crystal_shard", name = "Crystal Shard", element = "crystal", tier = 5, book = "quire" },
	{ key = "dragon_smokesculpture", name = "Dragon Smokesculpture", element = "smoke", tier = 5, book = "quire" },
	{ key = "flame_burst", name = "Flame Burst", element = "fire", tier = 5 },
	{ key = "garmentglimpse", name = "Garmentglimpse Glasses", element = "light", tier = 5 },
	{ key = "handheld_windowway", name = "Handheld Windowway", element = "light", tier = 5 },
	{ key = "levitation_spell", name = "Levitation Spell", element = "wind", tier = 5 },
	{ key = "lockwax", name = "Lockwax", element = "light", tier = 5 },
	{ key = "raincleaver", name = "Raincleaver", element = "light", tier = 5 },
	{ key = "rushing_wave", name = "Rushing Wave", element = "wind", tier = 5 },
	{ key = "sasaran_cloak", name = "Sasaran's Cloak", element = "light", tier = 5, book = "tome" },
	{ key = "sealchair", name = "Sealchair", element = "earth", tier = 5 },
	{ key = "skysoaring", name = "Skysoaring", element = "light", tier = 5, book = "quire" },
	{ key = "smokesculpting", name = "Smokesculpting", element = "smoke", tier = 5 },
	{ key = "torrential_flow", name = "Torrential Flow", element = "water", tier = 5 },
	{ key = "water_bolt", name = "Water Bolt Volley", element = "water", tier = 5 },
	{ key = "water_cage", name = "Water Cage", element = "water", tier = 5 },
	{ key = "wayward_whorlwind", name = "Wayward Whorlwind", element = "light", tier = 5 },
	{ key = "wind_wall", name = "Wind Wall", element = "wind", tier = 5 },
	{ key = "advanced_beastwarding", name = "Advanced Beastwarding", element = "crystal", tier = 6 },
	{ key = "amplification", name = "Amplification Scroll", element = "light", tier = 6 },
	{ key = "borrowshade", name = "Borrowshade", element = "smoke", tier = 6, book = "quire" },
	{ key = "expansion_levitation", name = "Seal of Expansion and Levitation", element = "light", tier = 6 },
	{ key = "leech_counterclock", name = "Valance Leech Counterclock", element = "light", tier = 6 },
	{ key = "mirror", name = "Mirror Spell", element = "light", tier = 6 },
	{ key = "mirror_cloak", name = "Mirror Cloak of Borrowshade", element = "light", tier = 6, book = "tome" },
	{ key = "spell_of_reduction", name = "Spell of Reduction", element = "flicker", tier = 6 },
	{ key = "sylph_shoes", name = "Sylph Shoes", element = "vacuum", tier = 6 },
	{ key = "windowway", name = "Windowway", element = "light", tier = 6 },
	{ key = "boilfire_dragon", name = "Boilfire Dragon", element = "water", tier = 7 },
	{ key = "counterclock", name = "Counterclock", element = "crystal", tier = 7 },
	{ key = "doorknob", name = "Doorknob Doorway", element = "light", tier = 7 },
	{ key = "magic_cookpot", name = "Magic Cookpot", element = "fireworks", tier = 7, book = "tome" },
	{ key = "pegasus_carriage", name = "Pegasus Carriage", element = "light", tier = 7, book = "tome" },
	{ key = "time_stop", name = "Time Stop", element = "light", tier = 7 },
	{ key = "water_dragon", name = "Water Dragon", element = "crystal", tier = 7 },
	{ key = "petrification", name = "Petrification", element = "light", tier = 7, book = "tome", forbidden = true },
	{ key = "dragons_labyrinth", name = "Dragon's Labyrinth", element = "smoke", tier = 7, book = "tome", forbidden = true },
	{ key = "memory_erasure", name = "Memory Erasure", element = "smoke", tier = 7, forbidden = true },
	{ key = "healingcraft", name = "Healingcraft", element = "ice", tier = 7, forbidden = true },
	{ key = "golem", name = "Golem", element = "earth", tier = 7, forbidden = true },
	{ key = "scalewolf_curse", name = "Scalewolf Curse", element = "light", tier = 7, forbidden = true },
	{ key = "anti_scalewolf", name = "Anti Scalewolf Curse", element = "ice", tier = 7, forbidden = true },
	{ key = "slime_rendering", name = "Slime Rendering", element = "mud", tier = 7, forbidden = true },
}
