"""What each part of a wiki seal's drawing is: the book names the part under the mouse on a grimoire page or a pasted
sheet (notebook.lua draw_parts). Reading a page there would take the game up to seconds, so it is read here, once, the
way the book reads a wiki's seal drawn by hand (seal.lua seal_parts: the parts its reading is sure of, their twins round
the ring, the seal's own glyphs); written to files/grimoire_parts.lua - each part's kind, key, whether inverted, and the
strokes it is drawn with (indices into grimoire_strokes( entry )).

    python tools/make_grimoire_parts.py      (needs: pip install lupa; run after tools/make_grimoire.py)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(MOD, "tests"))
import harness  # noqa: E402

OUT = os.path.join(MOD, "files", "grimoire_parts.lua")

READ = r'''
return function( entry )
    local strokes = grimoire_strokes( entry )
    local index = {}
    for i, stroke in ipairs( strokes ) do index[stroke] = i end
    local ok, tree, _, partial = pcall( parse_seal, strokes )
    local out = {}
    for _, part in ipairs( seal_parts( strokes, ok and ( tree or partial ) or nil, entry ) ) do
        local ids = {}
        for _, stroke in ipairs( part.strokes ) do
            if index[stroke] then ids[#ids + 1] = index[stroke] end
        end
        table.sort( ids )
        if #ids > 0 then
            out[#out + 1] = part.kind .. ":" .. part.key .. ":" .. ( part.inverted and 1 or 0 ) .. ":" .. table.concat( ids, "," )
        end
    end
    return table.concat( out, ";" )
end
'''


def main():
    lua = harness.load_reader()
    read = lua.execute(READ)
    lines, named, marks = [], 0, 0
    for entry in lua.eval("GRIMOIRE").values():
        text = read(entry)
        if text:
            lines.append(f'\t{entry["key"]} = "{text}",\n')
            for part in text.split(";"):
                if part.startswith("mark"):
                    marks += 1
                else:
                    named += 1
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by tools/make_grimoire_parts.py - do not edit by hand.\n"
                "-- What each part of a wiki seal's drawing is, for the book to name the part under the mouse (notebook.lua\n"
                "-- draw_parts): \"kind:key:inverted:strokes\" separated by ';', the strokes indices into grimoire_strokes( entry );\n"
                "-- kind 'mark': a glyph of the seal's own, not named (seal.lua seal_parts).\n"
                "GRIMOIRE_PARTS = {\n")
        f.writelines(lines)
        f.write("}\n")
    print(f"{len(lines)} seals: {named} parts named, {marks} marks of their own -> {OUT}")


if __name__ == "__main__":
    main()
